version: 2.1
jobs:
  build:
    docker:
      # Use the same Docker base as the project
      - image: python:3.7.3-stretch

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run lint!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint 
  - deploy:
      docker:
        - image: amazon/aws-cli
      
      steps:
        - checkout
        - run:
            name: build docker image
            command: |
              docker build -t {{ docker_image }} .
        - run:
            name: build & upload docker image
            command: |
              aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin
              docker tag {{ docker_image }} {{ docker_repo }}
              docker push {{ docker_repo }}
              docker logout
        - run:
            name: deploy to aws
            command: |
              kubectl 
workflows:
  build:
    jobs:
      - build
      - deploy: 
          requires:
            - "build"
          filters:
            branches:
              only: [main]
